name: CI Serverless
on: [push, pull_request, workflow_dispatch]
jobs:
  ci:
    name: Serverless (PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1', '8.2']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, dom, fileinfo, intl-73.2, sqlite3
          coverage: xdebug

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Install Composer dependencies
        run: composer install

      - name: Prepare the application
        run: php -r "file_exists('.env') || copy('.env.dist', '.env');"

      - name: Test with phpunit
        run: vendor/bin/phpunit --coverage-text
